---
- hosts: localhost
  vars:
    user_name: "{{ user_name | default('amaslenn') }}"

  roles:
  - role: packages
    tags: [packages]

  - role: zsh

  - role: vim
    tags: [vim]

  - role: dotfiles
    tags: [dotfiles]

  - role: user-settings
    tags: user-settings
