---
- hosts: localhost
  vars:
    user_name: "{{ user_name | default('amaslenn') }}"

  roles:
  - role: packages
    tags: [packages]

  - role: zsh
    tags: [zsh]

  - role: appstore
    tags: [appstore]

  - role: dotfiles
    tags: [dotfiles]

  - role: vim
    tags: [vim]
