---
- name: Make sure group 'wheel' exists
  group:
    name: wheel
    state: present
  become: yes
  become_user: sudo

- name: Make sure group 'sudo' exists
  group:
    name: sudo
    state: present
  become: yes
  become_user: root

- name: Allow group 'wheel' skip sudo pass
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '%wheel.*NOPASSWD'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
  become: yes
  become_user: root

- name: Create user
  user:
    name: amaslenn
    shell: /bin/zsh
    password: "{{ 'pass' | password_hash('sha512') }}"
    force: yes
    groups: "sudo,wheel"
  become: yes
  become_user: root

- name: Keep values of proxies for sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: 'LIBVA'
    line: 'Defaults    env_keep += "http_proxy https_proxy"'
  become: yes
  become_user: root

