---
- name: "[Debian] Install packages"
  package:
    name: ["cifs-utils", "vim", "git", "mc", "zsh", "automake"]
    state: present
  become: yes

- name: "[Debian] more packages"
  package:
    name: ["build-essential", "curl"]
    state: present
  become: yes
