---
- name: Add brew repos
  homebrew_tap:
    name:
     - microsoft/git
     - homebrew/cask-fonts

- name: Install terminal apps
  homebrew:
    name:
      - zsh
      - git
      - gh
      - ipython
      - tmux
      - fzf
      - ripgrep

- name: Fonts
  homebrew:
    name:
      - font-cascadia-code
      - font-monofur-nerd-font
      - font-inconsolata
      - svn   # required for Source Code Pro
      - font-source-code-pro

- name: Install dev GUI apps
  homebrew_cask:
    name:
      - iterm2
      - visual-studio-code
    accept_external_apps: yes

- name: Other tools & apps (cask)
  homebrew_cask:
    name:
      - microsoft-edge
      - git-credential-manager-core
    accept_external_apps: yes
