---
- name: Add Microsoft Git repo
  homebrew_tap:
    name: microsoft/git

- name: Install terminal apps
  homebrew:
    name:
      - zsh
      - git
      - gh
      - ipython
      - tmux
      - fzf
      - ripgrep

- name: Install dev GUI apps
  homebrew_cask:
    name:
      - iterm2
      - visual-studio-code
    accept_external_apps: yes

- name: Other tools & apps (cask)
  homebrew_cask:
    name:
      - ilya-birman-typography-layout
      # - remembear — there is no cask for it :(
      - zoom
      - microsoft-edge
      - git-credential-manager-core
    accept_external_apps: yes
