---
- name: Install terminal apps
  homebrew:
    name:
      - zsh
      - git
      - gh
      - ipython
      - tmux
      - fzf
      - ripgrep

- name: Install dev GUI apps
  homebrew_cask:
    name:
      - iterm2
      - visual-studio-code
    accept_external_apps: yes

- name: Other tools & apps
  homebrew_cask:
    name:
      - ilya-birman-typography-layout
      # - remembear — there is no cask for it :(
      - zoom
      - microsoft-edge
    accept_external_apps: yes
