---
- name: Include RHEL tasks
  include: rhel.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian tasks
  include: debian.yml
  when: ansible_os_family == "Debian"

- name: Include MacOS tasks
  include: macos.yml
  when: ansible_os_family == "Darwin"
