---
- name: Install oh-my-zsh
  shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: Create ~/.oh-my-zsh/custom dirs
  file:
    path: '~/.oh-my-zsh/custom/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - 'plugins'
    - 'themes'

- name: Install plugins
  git:
    repo: 'https://github.com/zsh-users/{{ item }}.git'
    dest: ~/.oh-my-zsh/custom/plugins/{{ item }}
  with_items:
    - 'zsh-syntax-highlighting'
    - 'zsh-autosuggestions'

- name: fzf clone
  git:
    repo: 'https://github.com/junegunn/fzf'
    dest: '~/.fzf'

- name: fzf install
  shell: '~/.fzf/install --all'

- name: Install my theme
  git:
    repo: 'https://github.com/amaslenn/bureau-am.git'
    dest: ~/.oh-my-zsh/custom/themes/bureau-am

- name: Update ~/.zshrc
  blockinfile:
    create: yes
    dest: ~/.zshrc
    insertafter: EOF
    block: "{% raw %}

      setopt hist_ignore_all_dups

      alias hist='history | grep '

      alias tmux='TERM=xterm-256color tmux'

      {% endraw %}"

- name: Setup theme
  lineinfile:
    dest: ~/.zshrc
    state: present
    regexp: 'ZSH_THEME'
    line: 'ZSH_THEME="bureau-am/bureau-am"'

- name: Enable plugins
  lineinfile:
    dest: ~/.zshrc
    state: present
    regexp: 'plugins='
    line: 'plugins=(git zsh-syntax-highlighting zsh-autosuggestions)'
