---
- name: Install oh-my-zsh
  shell: |
    [ -d ~/.oh-my-zsh ] && exit 0
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Create ~/.oh-my-zsh/custom dirs
  file:
    path: '~/.oh-my-zsh/custom/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - 'plugins'
    - 'themes'

- name: Install plugins
  git:
    repo: 'https://github.com/zsh-users/{{ item }}.git'
    dest: ~/.oh-my-zsh/custom/plugins/{{ item }}
  with_items:
    - 'zsh-syntax-highlighting'
    - 'zsh-autosuggestions'

- name: fzf clone
  git:
    repo: 'https://github.com/junegunn/fzf'
    dest: '~/.fzf'

- name: fzf install
  shell: '~/.fzf/install --all'

- name: Install my theme
  git:
    repo: 'https://github.com/amaslenn/bureau-am.git'
    dest: ~/.oh-my-zsh/custom/themes/bureau-am

- name: Update ~/.zshrc
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { line: 'export TERM=xterm-256color' }
    - { line: 'setopt hist_ignore_all_dups' }
    - { line: "alias hist='history | grep '" }
    - { line: "alias tmux='TERM=xterm-256color tmux'" }

- name: Setup theme
  lineinfile:
    dest: ~/.zshrc
    state: present
    regexp: 'ZSH_THEME'
    line: 'ZSH_THEME="bureau-am/bureau-am"'

- name: Install tmux tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: ~/.tmux/plugins/tpm

- name: Enable plugins
  lineinfile:
    dest: ~/.zshrc
    state: present
    regexp: 'plugins='
    line: 'plugins=(git zsh-syntax-highlighting zsh-autosuggestions)'
