---
- name: Update `.tmux.conf`
  copy:
    src: .tmux.conf
    dest: ~/.tmux.conf

- name: Install `monofur` font
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/{{ item }}
  with_items:
    - monof55.ttf
    - monof56.ttf
  become: yes
  become_user: root
