---
- name: Install `monofur` font
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/{{ item }}
  with_items:
    - monof55.ttf
    - monof56.ttf
  when: ansible_os_family != "Darwin"
  become: yes

- name: Include MacOS tasks
  include: macos.yml
  when: ansible_os_family == "Darwin"
