---
- name: Install `monofur` font
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/{{ item }}
  with_items:
    - monof55.ttf
    - monof56.ttf
  when: ansible_distribution != 'MacOSX'
  become: yes
  become_user: root

- name: Get my dotfiles
  git:
    repo: 'https://github.com/amaslenn/dotfiles.git'
    dest: ~/.my-dotfiles-repo

- name: Install my dotfiles
  copy:
    src: "~/.my-dotfiles-repo/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - '.gitconfig'
    - '.tmux.conf'
    - '.vimrc'

- name: VimPlug
  shell: 'curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
