---
# This role expects VIM to be installed and .vimrc filled with a list of plugins

- name: Create ~/.vim/autoload/
  file:
    path: ~/.vim/autoload/
    state: directory

- name: Pull VimPlug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Install Vim plugins
  shell: vim -E -s -u "$HOME/.vimrc" +PlugInstall +qall
