---
# This role expects VIM to be installed and .vimrc filled with a list of plugins

- name: Pull VimPlug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Install Vim plugins
  shell: vim +'PlugInstall --sync' +qa
