---
- name: Create Installed Packages directory
  file:
    name: "{{ installed_packages }}"
    state: directory

- name: Install Package Control
  get_url:
    url: "http://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ installed_packages }}/Package Control.sublime-package"

- name: Create Packages/User directory
  file:
    name: "{{ packages_user }}"
    state: directory

- name: Copy user Preferences
  copy:
    src: Preferences.sublime-settings
    dest: "{{ packages_user }}/"
    force: no

- name: Copy user Package Control Preferences
  copy:
    src: "Package Control.sublime-settings"
    dest: "{{ packages_user }}/"
    force: no

