---
- name: Add Sublime Text apt key
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes
  become_user: root

- name: Add Sublime Text apt repo
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
  become: yes
  become_user: root

- name: Install Sublime Text 3
  package:
    name: sublime-text
    state: installed
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'
  become: yes
  become_user: root

- name: Create Installed Packages directory
  file:
    name: "{{ installed_packages }}"
    state: directory

- name: Install Package Control
  get_url:
    url: "http://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ installed_packages }}/Package Control.sublime-package"

- name: Create Packages/User directory
  file:
    name: "{{ packages_user }}"
    state: directory

- name: Copy user Preferences
  copy:
    src: Preferences.sublime-settings
    dest: "{{ packages_user }}/"
    force: no

- name: Copy user Package Control Preferences
  copy:
    src: "Package Control.sublime-settings"
    dest: "{{ packages_user }}/"
    force: no

